### ISSUE TITLE
pressing tag cloud tags does not work on non-default theme

### ISSUE THREAD

**Issue by chakkimatti** [RobertHeim/phpbb-ext-topictags#44]
I'm using pbtech as the theme and the tag cloud tags on Board index do not work, tags listed under the posts (inside a forum) do. When logged in as admin and using the forum with the default theme (prosilver) they all work.

**Comment by RobertHeim** [comment]
Hi, other themes than prosilver won't be supported, unless the style author does ensure compliance to prosilver.

Am 17. Februar 2015 20:29:57 MEZ, schrieb Aron Elal <notifications@github.com>:
