### ISSUE TITLE
SQL ERROR tag_lowercase

### ISSUE THREAD

**Issue by LordBeaver** [RobertHeim/phpbb-ext-topictags#48]
**When add a tag:**
>SQL ERROR [ mysqli ]
>
>Unknown column 'tag_lowercase' in 'field list' [1054]
>
>SQL
>
>INSERT INTO phpbb_rh_topictags_tag (tag, tag_lowercase) VALUES ('Питомцы', 'питомцы')
>
>BACKTRACE
>
>FILE: (not given by php)
>LINE: (not given by php)
>CALL: msg_handler()
>
>FILE: [ROOT]/phpbb/db/driver/driver.php
>LINE: 855
>CALL: trigger_error()
>
>FILE: [ROOT]/phpbb/db/driver/mysqli.php
>LINE: 194
>CALL: phpbb\db\driver\driver->sql_error()
>
>FILE: [ROOT]/phpbb/db/driver/driver.php
>LINE: 650
>CALL: phpbb\db\driver\mysqli->sql_query()
>
>FILE: [ROOT]/ext/robertheim/topictags/service/tags_manager.php
>LINE: 370
>CALL: phpbb\db\driver\driver->sql_multi_insert()
>
>FILE: [ROOT]/ext/robertheim/topictags/service/tags_manager.php
>LINE: 318
>CALL: robertheim\topictags\service\tags_manager->create_missing_tags()
>
>FILE: [ROOT]/ext/robertheim/topictags/event/main_listener.php
>LINE: 176
>CALL: robertheim\topictags\service\tags_manager->assign_tags_to_topic()
>
>FILE: (not given by php)
>LINE: (not given by php)
>CALL: robertheim\topictags\event\main_listener->submit_post_end()
>
>FILE: [ROOT]/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php
>LINE: 164
>CALL: call_user_func()
>
>FILE: [ROOT]/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php
>LINE: 53
>CALL: Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()
>
>FILE: [ROOT]/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php
>LINE: 167
>CALL: Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
>
>FILE: [ROOT]/phpbb/event/dispatcher.php
>LINE: 60
>CALL: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch()
>
>FILE: [ROOT]/phpbb/event/dispatcher.php
>LINE: 46
>CALL: phpbb\event\dispatcher->dispatch()
>
>FILE: [ROOT]/includes/functions_posting.php
>LINE: 2432
>CALL: phpbb\event\dispatcher->trigger_event()
>
>FILE: [ROOT]/posting.php
>LINE: 1394
>CALL: submit_post()

**When open /tag/*tagname*:**
>SQL ERROR [ mysqli ]
>
>Unknown column 't.tag_lowercase' in 'where clause' [1054]
>
>SQL
>
>SELECT COUNT(*) as total_results FROM (SELECT topics.* FROM phpbb_topics topics JOIN phpbb_rh_topictags tt ON tt.topic_id = topics.topic_id JOIN phpbb_rh_topictags_tag t ON tt.tag_id = t.id JOIN phpbb_forums f ON f.forum_id = topics.forum_id WHERE t.tag_lowercase = 'обсуждение' AND f.rh_topictags_enabled = 1 AND topics.forum_id IN (7, 9, 10, 23, 25, 26, 28, 29, 50, 52, 53, 54, 56, 57, 58, 60, 63, 64, 65, 66, 67, 68, 69, 70, 71) AND topics.topic_visibility = 1 GROUP BY topics.topic_id HAVING count(t.id) = 1) a
>
>BACKTRACE
>
>FILE: (not given by php)
>LINE: (not given by php)
>CALL: msg_handler()
>
>FILE: [ROOT]/phpbb/db/driver/driver.php
>LINE: 855
>CALL: trigger_error()
>
>FILE: [ROOT]/phpbb/db/driver/mysqli.php
>LINE: 194
>CALL: phpbb\db\driver\driver->sql_error()
>
>FILE: [ROOT]/ext/robertheim/topictags/service/tags_manager.php
>LINE: 480
>CALL: phpbb\db\driver\mysqli->sql_query()
>
>FILE: [ROOT]/ext/robertheim/topictags/controller/main.php
>LINE: 137
>CALL: robertheim\topictags\service\tags_manager->count_topics_by_tags()
>
>FILE: (not given by php)
>LINE: (not given by php)
>CALL: robertheim\topictags\controller\main->show_tag()
>
>FILE: [ROOT]/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php
>LINE: 117
>CALL: call_user_func_array()
>
>FILE: [ROOT]/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php
>LINE: 61
>CALL: Symfony\Component\HttpKernel\HttpKernel->handleRaw()
>
>FILE: [ROOT]/app.php
>LINE: 33
>CALL: Symfony\Component\HttpKernel\HttpKernel->handle()

**Comment by RobertHeim** [comment]
Disable extension, delete data of ext, delete files of ext, reinstall ext.
Note that you are using an unreleased version that is under development and which may break all your data.

Am 4. März 2015 08:04:41 MEZ, schrieb LordBeaver <notifications@github.com>:
