### ISSUE TITLE
URLs keep getting re-written after option has been disabled in server settings 

### ISSUE THREAD

**Issue by forkless** [RobertHeim/phpbb-ext-topictags#52]
PHPBB 3.1.4
Topic Tags 0.1.3-b1

After disabling URL rewriting, the cloud footer keeps it re-writing as /tags 

- Clearedall phpbb cache
- Restarted MySQL
- Restarted Apache

Still it shows the re-written URL

- Restarted server

Same result

Other extensions seem to stop re-writting just nicely.

PS. Love the extention! Best thing since sliced bread for phpbb if you ask me.

**Comment by RobertHeim** [comment]
Thanks for report!
