### ISSUE TITLE
Tag is not stored when entered during new topic creation

### ISSUE THREAD

**Issue by RobertHeim** [RobertHeim/phpbb-ext-topictags#59]

**Comment by RobertHeim** [comment]
This: https://github.com/RobertHeim/phpbb-ext-topictags/blob/master/event/main_listener.php#L172

should be: 

	$mode = $data['mode'];
	$is_new_topic = $mode == 'post';
	if ($is_new_topic || $this->is_edit_first_post($event_data['mode'], $data))

**Comment by nerestaren** [comment]
Please, consider removing/upgrading the "latest release" from https://github.com/RobertHeim/phpbb-ext-topictags/releases, as I downloaded that instead of master and went kinda crazy.

Cheers!
