### ISSUE TITLE
Tag suggestions not showing up

### ISSUE THREAD

**Issue by vulfgang** [RobertHeim/phpbb-ext-topictags#75]
Testing locally, the tag suggestions list don't seem to show up at all. I can see the fake 404 popping up in my dev console so I think the request is probably sending fine, but no list/dropdown shows up at all. I tried purging the cache to see if it might've been the same issue as the ACP whitelist but that didn't do anything.

Also, I haven't looked around the code extensively yet but I did see [this line](https://github.com/RobertHeim/phpbb-ext-topictags/blob/master/controller/main.php#L283). Might have something to do with this issue. Or it could be something wrong on my end.

**Comment by RobertHeim** [comment]
Thx for report!

**Comment by vulfgang** [comment]
Updated the files but the suggestion list still does not show up. I actually tried rolling back to release v1.0.1 and v1.0.0 and the list still wasn't showing up so if it works for you it might be something on my end (working locally). Any ideas?

**Comment by RobertHeim** [comment]
do you still see 404 ?

**Comment by vulfgang** [comment]
Yes

**Comment by RobertHeim** [comment]
have you cleared the cache after update?

**Comment by vulfgang** [comment]
Yes, made sure to clear it every time in case it was just a frontend issue.

**Comment by RobertHeim** [comment]
I cannot reproduce it.. maybe test in an other environment if you can reproduce it.

**Comment by vulfgang** [comment]
Both a friend of mine and I were able to reproduce it in different environments. Right now, I'm thinking it might be a dependency issue. What specifically do we need installed for the extension?
