### ISSUE TITLE
Filter out tags (at least in searches) - configurable in user profile

### ISSUE THREAD

**Issue by harerama** [RobertHeim/phpbb-ext-topictags#76]
Hi, thanks for this extension - it is great !
I would love to be able to filter out content by default in most places of phpBB based on tags.
The idea would be to have a user-defined list of tags to be filtered out in the user profile.

I am more than willing to help on this but I am new to phpbb dev (an certainly not an experienced php dev either).

**Comment by RobertHeim** [comment]
I don't see this being a common useful feature. You might want to implement your own extension that extends mine, see https://www.phpbb.com/community/viewtopic.php?f=461&t=2240106
